/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-16 10:29:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;
import data.dao.MemberDao;
import data.dto.MemberDto;
import data.dao.CartDao;
import data.dto.CartDto;

public final class cartPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.MemberDao");
    _jspx_imports_classes.add("data.dto.MemberDto");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("data.dao.CartDao");
    _jspx_imports_classes.add("data.dto.CartDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"https://unpkg.com/tailwindcss@1.2.0/dist/tailwind.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../iconsource/all.min.css\">\r\n");
      out.write("<script src=\"../iconsource/all.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>cart</title>\r\n");
      out.write("\r\n");


//로그인 상태확인
String loginok=(String)session.getAttribute("loginok");

String myid="";
CartDto cdto=new CartDto();
CartDao cdao=new CartDao();
//로그인 상태라면 아이디 가져오기
if(loginok!=null){
	myid=(String)session.getAttribute("myid");
	
	//사용자 member_dto 가져오기
	MemberDao mdao=new MemberDao();
	MemberDto mdto=mdao.getMemberById(myid);
	System.out.print(mdto.getMember_name()+"님의 메일은 "+mdto.getMember_email()+"입니다.");
}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	/*체크박스모양 바꾸기*/\r\n");
      out.write("	input[type=\"checkbox\"] {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    display:none;\r\n");
      out.write("	    appearance: none;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"] {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    width: 25px;\r\n");
      out.write("	    height: 25px;\r\n");
      out.write("	\r\n");
      out.write("		margin: -2px 10px 0 0;\r\n");
      out.write("	\r\n");
      out.write("	    vertical-align: middle;\r\n");
      out.write("	\r\n");
      out.write("	    background-size: cover;\r\n");
      out.write("	    \r\n");
      out.write("	    background: url(../imgsource/checkbox_default.png) no-repeat;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"]:checked {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	     background-size: cover;\r\n");
      out.write("	     \r\n");
      out.write("	     background: url(../imgsource/checkbox_checked.png) no-repeat;\r\n");
      out.write("	     \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"]:focus {\r\n");
      out.write("		outline:none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* Chrome, Safari, Edge, Opera */\r\n");
      out.write("	input::-webkit-outer-spin-button,\r\n");
      out.write("	input::-webkit-inner-spin-button {\r\n");
      out.write("	  	-webkit-appearance: none;\r\n");
      out.write("	  	margin: 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* Firefox */\r\n");
      out.write("	input[type=number] {\r\n");
      out.write("	  -moz-appearance: textfield;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	div.container{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.cartwrapper{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		width: 1000px;\r\n");
      out.write("		height: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.cartwrapper>div{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.cartlist_div{\r\n");
      out.write("		width: 70%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.cartlist_header{\r\n");
      out.write("		border-bottom: 1px solid black;\r\n");
      out.write("		padding-bottom: 10px;\r\n");
      out.write("		margin-left: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	span.line{\r\n");
      out.write("		color: lightgray;\r\n");
      out.write("		padding: 0px 20px 0px 20px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.content{\r\n");
      out.write("		margin-top: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.title{\r\n");
      out.write("		margin-left: 10px;\r\n");
      out.write("		height: 35px;\r\n");
      out.write("		line-height: 35px;\r\n");
      out.write("		margin-bottom: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.title>span{\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin-right: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.icon{\r\n");
      out.write("		padding: 0px 3px 6px 5px;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.nextline{\r\n");
      out.write("		clear: both;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.categoryTitle{\r\n");
      out.write("		font-size: 13pt;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.list_content{\r\n");
      out.write("		margin-left: 10px;\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/*\r\n");
      out.write("	.list_content>div{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}*/\r\n");
      out.write("	\r\n");
      out.write("	.item_check{\r\n");
      out.write("		width: 5%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.item_img{\r\n");
      out.write("		width: 10%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.item_name{\r\n");
      out.write("		width: 45%;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.item_cnt{\r\n");
      out.write("		width: 100px;\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		float: left;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.item_price{\r\n");
      out.write("		width: 19%;\r\n");
      out.write("		height: 50px;\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.itemDel{\r\n");
      out.write("		width: 7%;\r\n");
      out.write("		text-align: right;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cnt_btn_wrapper{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 30px;\r\n");
      out.write("		line-height: 30px;\r\n");
      out.write("		float: left;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		border: 1px solid lightgray;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	button:focus{\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.cnt_btn{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		font-size: 13pt;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		padding: 0px 5px 0px 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#cart_cnt{\r\n");
      out.write("		width: 20%;\r\n");
      out.write("	  	text-align: center;\r\n");
      out.write("	  	background: none;\r\n");
      out.write("	  	font-size: 13pt;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	\r\n");
      out.write("	//체크박스 옆 글자선택해도 체크박스 선택되게\r\n");
      out.write("	$(\"b.allCheck\").click(function(){\r\n");
      out.write("	\r\n");
      out.write("		if($(\"input.allCheck\").is(\":checked\")){\r\n");
      out.write("			$(\"input.allCheck\").attr(\"checked\",false);\r\n");
      out.write("		}else{\r\n");
      out.write("			$(\"input.allCheck\").attr(\"checked\",\"checked\");\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function cartList(){\r\n");
      out.write("	$(\".cnt_plus\").click(function(){\r\n");
      out.write("		$(\"#cart_cnt\").trigger(\"click\");\r\n");
      out.write("	})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"cartwrapper\">\r\n");
      out.write("			<!-- 왼쪽 장바구니 목록창 -->\r\n");
      out.write("			<div class=\"cartlist_div\">\r\n");
      out.write("				<div class=\"cartlist_header\">\r\n");
      out.write("					<b class=\"allCheck\"><input type=\"checkbox\" class=\"allCheck\">&nbsp;전체선택(1/1)</b>\r\n");
      out.write("					<span class=\"line\">|</span>\r\n");
      out.write("					<span id=\"selDel\">선택삭제</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"cartlist_content\">\r\n");
      out.write("					<div class=\"cartlist_cold content\">\r\n");
      out.write("						<div class=\"cold_title title\">\r\n");
      out.write("							<!-- 폰트어썸 -->\r\n");
      out.write("							<span class=\"icon\"><i class=\"fa-solid fa-droplet fa-xl\"\r\n");
      out.write("							 style=\"color: green;\"></i></span>\r\n");
      out.write("							<span class=\"categoryTitle\"><b>냉장 상품</b></span>\r\n");
      out.write("							<div class=\"nextline\"></div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 장바구니에 담긴 냉장 상품 -->\r\n");
      out.write("							<div class=\"list_content\">\r\n");
      out.write("								<table style=\"width: 100%\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td class=\"item_check\">\r\n");
      out.write("											<input type=\"checkbox\" class=\"\">\r\n");
      out.write("										</td>\r\n");
      out.write("										<td class=\"item_img\">\r\n");
      out.write("											<img alt=\"\" src=\"\">\r\n");
      out.write("										</td>\r\n");
      out.write("										<td class=\"item_name\">\r\n");
      out.write("											<span>상품명</span>\r\n");
      out.write("										</td>\r\n");
      out.write("										<td class=\"item_cnt\">\r\n");
      out.write("											<div class=\"cnt_btn_wrapper\">\r\n");
      out.write("												<button class=\"cnt_btn cnt_minus\">\r\n");
      out.write("													-\r\n");
      out.write("												</button>\r\n");
      out.write("												<input type=\"number\" id=\"cart_cnt\" value=\"1\" min=\"1\">\r\n");
      out.write("												<button class=\"cnt_btn cnt_plus\">\r\n");
      out.write("													+\r\n");
      out.write("												</button>\r\n");
      out.write("											</div>\r\n");
      out.write("										</td>\r\n");
      out.write("										<td class=\"item_price\">\r\n");
      out.write("											<span>10,000원</span>\r\n");
      out.write("										</td>\r\n");
      out.write("										<td class=\"itemDel\">\r\n");
      out.write("											<button type=\"button\">X</button>\r\n");
      out.write("										</td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"nextline\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"cartlist_header\"></div>\r\n");
      out.write("					<div class=\"nextline\"></div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"cartlist_freeze content\">\r\n");
      out.write("						<div class=\"freeze_title title\">\r\n");
      out.write("							<span class=\"icon\"><i class=\"fa-regular fa-snowflake fa-xl\"\r\n");
      out.write("							 style=\"color: skyblue;\"></i></span>\r\n");
      out.write("							<span class=\"categoryTitle\"><b>냉동 상품</b></span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 오른쪽 배송지/금액/주문창  -->\r\n");
      out.write("			<div class=\"order_div\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
