/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-20 08:39:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.detail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dto.ItemDto;
import java.util.List;
import data.dao.ItemDao;

public final class detailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dto.ItemDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.dao.ItemDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	  \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/good_view.css\">\r\n");
      out.write("<link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css2?family=Anton&family=Edu+VIC+WA+NT+Beginner:wght@600&family=Gamja+Flower&family=Single+Day&family=Jua&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../review/review.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("    <script src=\"../js/detail.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");

	String item_num=request.getParameter("item_num");
    ItemDao dao=new ItemDao();
     ItemDto dto=dao.getItemData(item_num); 
    


      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 시작 -->\r\n");
      out.write("<div id=\"container\" class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("            <div id=\"content\" style=\"opacity: 1;\">\r\n");
      out.write("                <div class=\"section_view\">\r\n");
      out.write("                    <div id=\"sectionView\">\r\n");
      out.write("                        <div class=\"inner_view\">\r\n");
      out.write("                            <div class=\"thumb\" >\r\n");
      out.write("                                <img src=\"../save-info-img/");
      out.print(dto.getItem_img());
      out.write("\" alt=\"\" class=\"bg\">\r\n");
      out.write("										\r\n");
      out.write("										\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"goods_name\">\r\n");
      out.write("                               \r\n");
      out.write("                                <strong class=\"name\">");
      out.print(dto.getItem_name() );
      out.write("</strong>\r\n");
      out.write("                                <span class=\"short_desc\">");
      out.print(dto.getItem_sub_title() );
      out.write("</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"goods_price\">\r\n");
      out.write("                                <span class=\"position\">\r\n");
      out.write("                                    <span class=\"dc\">\r\n");
      out.write("                                      \r\n");
      out.write("                                        <span class=\"dc_price\">\r\n");
      out.write("                                          \r\n");
      out.write("                                         \r\n");
      out.write("                                            <input type=\"hidden\" value=0>    ");
      out.print(dto.getItem_price());
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"won\">원</span>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    \r\n");
      out.write("                                </span>\r\n");
      out.write("                                \r\n");
      out.write("                            </p>\r\n");
      out.write("                            <div class=\"goods_info\">\r\n");
      out.write("                           \r\n");
      out.write("                                <dl class=\"list fst\">\r\n");
      out.write("                                \r\n");
      out.write("                                    <dt class=\"tit\">판매단위</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_sell_unit() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">중량/용량</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_weight() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">배송구분</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_package_detail() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">원산지</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_origin() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">포장타입</dt>\r\n");
      out.write("                                    <dd class=\"desc\">\r\n");
      out.write("                                        ");
      out.print(dto.getItem_package_type() );
      out.write("\r\n");
      out.write("                                        <strong class=\"emphd\"></strong>\r\n");
      out.write("                                    </dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">알레르기정보</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_allergy() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                                <dl class=\"list\">\r\n");
      out.write("                                    <dt class=\"tit\">안내사항</dt>\r\n");
      out.write("                                    <dd class=\"desc\">");
      out.print(dto.getItem_warning() );
      out.write("</dd>\r\n");
      out.write("                                </dl>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"cartPut\">\r\n");
      out.write("                        <div class=\"cart_option cart_type2\">\r\n");
      out.write("                            <form action=\"\">\r\n");
      out.write("                                <div class=\"inner_option\">\r\n");
      out.write("                                    <div class=\"in_option\">\r\n");
      out.write("                                        <div class=\"list_goods\">\r\n");
      out.write("                                            <ul class=\"list list_nopackage\">\r\n");
      out.write("                                                <li class=\"on\">\r\n");
      out.write("                                                    <span class=\"tit_item\">구매수량</span>\r\n");
      out.write("                                                    <div class=\"option\">\r\n");
      out.write("                                                        <span class=\"count\">\r\n");
      out.write("                                                            <button type=\"button\" class=\"btn down on\">수량내리기</button>\r\n");
      out.write("                                                            <input type=\"number\" readonly=\"readonly\" value = 1 class=\"inp\">\r\n");
      out.write("                                                            <button  type=\"button\" class=\"btn up on\">수량올리기</button>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"total\">\r\n");
      out.write("                                            <div class=\"price\">\r\n");
      out.write("                                                <strong class=\"tit\">총 상품금액 :</strong>\r\n");
      out.write("                                                <span class=\"sum\">\r\n");
      out.write("                                                    <span class=\"num\">");
      out.print(dto.getItem_price() );
      out.write("</span>\r\n");
      out.write("                                                    <span class=\"won\">원</span>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"group_btn off\">\r\n");
      out.write("                                        <div class=\"view_function\" >\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn_save\"><img alt=\"찜 목록\" src=\"/image/heart.png \" style=\"width: 30px; margin-bottom: 10px ;\"  ></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"btn_type1\">\r\n");
      out.write("                                            <button type=\"submit\" class=\"txt_type\" style=\"background-color: #4B62D3;\">장바구니 담기</button>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"layout-wrapper goods-view-area\"> <!-- $$$$$ -->\r\n");
      out.write("                   \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"goods-view-infomation detail_wrap_outer\" id=\"goods-view-infomation\">\r\n");
      out.write("                        <ul class=\"goods-view-infomation-tab-group\" style=\"margin-left: 20%;\" >\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-description\" class=\"goods-view-infomation-tab-anchor __active\">상품설명</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-infomation\" class=\"goods-view-infomation-tab-anchor\">상세정보</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-review\" class=\"goods-view-infomation-tab-anchor\">\r\n");
      out.write("                                    고객후기\r\n");
      out.write("                                    <span class=\"count_review\">(0)</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                         \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"goods-view-infomation-content __active\" id=\"goods-description\">\r\n");
      out.write("                            <div class=\"goods_wrap\">\r\n");
      out.write("                                <div class=\"goods_intro\">\r\n");
      out.write("                                    <div class=\"pic\">\r\n");
      out.write("                                        <img src=\"../save-img/");
      out.print(dto.getItem_img());
      out.write("\" style=\"width:1010px; height:671px;\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"context last\">\r\n");
      out.write("                                        <h3>\r\n");
      out.write("                                            <small>\r\n");
      out.write("                                                제목 부연설명\r\n");
      out.write("                                            </small>\r\n");
      out.write("                                            제목\r\n");
      out.write("                                        </h3>\r\n");
      out.write("                                        <p class=\"words\">\r\n");
      out.write("                                            샬라샬라 설명\r\n");
      out.write("                                        </p>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"goods_point\">\r\n");
      out.write("                                    <h3>\r\n");
      out.write("                                        <span>새벽마켓's Check Point</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <div class=\"context last\">\r\n");
      out.write("                                        <div class=\"pic\">\r\n");
      out.write("                                            <img src=\"\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"goods_tip\">\r\n");
      out.write("                                    <h3>\r\n");
      out.write("                                        <span>새벽마켓's Tip</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <div class=\"tip_box\">\r\n");
      out.write("                                        <div class=\"context last\">\r\n");
      out.write("                                            <div class=\"pic\">\r\n");
      out.write("                                                <img src=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"goods_pick\">\r\n");
      out.write("                                    <h3>\r\n");
      out.write("                                        <span>새벽마켓`s Pick</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"context last\">\r\n");
      out.write("                                        <p class=\"words\">\r\n");
      out.write("                                            <strong class=\"sub_tit\">\r\n");
      out.write("                                                <span class=\"option_tit\">상품명</span>\r\n");
      out.write("                                            </strong>\r\n");
      out.write("                                            <b>중량</b>\r\n");
      out.write("                                            : 중량샬라샬라\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <b>특징</b>\r\n");
      out.write("                                            : 특징샬라샬라\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <b>보관법</b>\r\n");
      out.write("                                            : 보관법샬라샬라\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            <b>조리법</b>\r\n");
      out.write("                                            : 조리법샬라샬라\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"goods_tip\">\r\n");
      out.write("                                    <h3>\r\n");
      out.write("                                        <span>Kurly's Tip</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <div class=\"tip_box\">\r\n");
      out.write("                                        <div class=\"context\">\r\n");
      out.write("                                            <div class=\"pic\">\r\n");
      out.write("                                                <img src=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p class=\"words\">\r\n");
      out.write("                                                <strong>요리 어떻게하는지 적는칸</strong>\r\n");
      out.write("                                                \r\n");
      out.write("                                                자세한설명 적는칸\r\n");
      out.write("                                                \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"about_brand\">\r\n");
      out.write("                                    <h3>\r\n");
      out.write("                                        <span>About Brand</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <div class=\"context last\">\r\n");
      out.write("                                        <div class=\"context_about\">\r\n");
      out.write("                                            <div class=\"pic\">\r\n");
      out.write("                                                <img src=\"\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p class=\"words\">\r\n");
      out.write("                                                \r\n");
      out.write("                                              브랜드 설명 적는칸\r\n");
      out.write("                                            </p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"goods-view-infomation-tab-group\">\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-description\" class=\"goods-view-infomation-tab-anchor\">상품설명</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-infomation\" class=\"goods-view-infomation-tab-anchor\">상세정보</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-review\" class=\"goods-view-infomation-tab-anchor\">\r\n");
      out.write("                                    고객후기\r\n");
      out.write("                                    <span class=\"count_review\">(0)</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"goods-view-infomation-content\" id=\"goods-image\">\r\n");
      out.write("                            <div id=\"goods_pi\">\r\n");
      out.write("                                <p class=\"pic\">\r\n");
      out.write("                                    <img src=\"\">\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"goods-view-infomation-tab-group\">\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-description\" class=\"goods-view-infomation-tab-anchor\">상품설명</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-infomation\" class=\"goods-view-infomation-tab-anchor __active\">상세정보</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-review\" class=\"goods-view-infomation-tab-anchor\">\r\n");
      out.write("                                    고객후기\r\n");
      out.write("                                    <span class=\"count_review\">(0)</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"goods-view-infomation-content\" id=\"goods-infomation\">\r\n");
      out.write("                            <table class=\"extra-information\">\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">포장단위별 용량(중량), 수량, 크기</th>\r\n");
      out.write("                                        <td>");
      out.print(dto.getItem_weight() );
      out.write("</td>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">관련법상 표시사항</th>\r\n");
      out.write("                                        <td>GAP, 무농약 인증</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">생산자, 수입품의 경우 수입자를 함께 표기</th>\r\n");
      out.write("                                        <td>제품 별도 라벨 표기 참조</td>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">상품구성</th>\r\n");
      out.write("                                        <td>");
      out.print(dto.getItem_name() );
      out.write("</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">농수산물의 원산지 표시에 관한 법률에 따른 원산지</th>\r\n");
      out.write("                                        <td>국산</td>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">보관방법 또는 취급방법</th>\r\n");
      out.write("                                        <td>");
      out.print(dto.getItem_package_type() );
      out.write("</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">제조연월일(포장일 또는 생산연도), 유통기한 또는 품질유지기한</th>\r\n");
      out.write("                                        <td>제품 별도 라벨 표기 참조</td>\r\n");
      out.write("                                        <th scope=\"row\" class=\"goods-view-form-table-heading\">소비자상담 관련 전화번호</th>\r\n");
      out.write("                                        <td>새벽마켓 고객행복센터(1644-1107)</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            <div class=\"whykurly_area\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <strong class=\"tit_whykurly\">WHY 새벽마켓</strong>\r\n");
      out.write("                                    <div id=\"why_kurly\" class=\"txt_area\">\r\n");
      out.write("                                        <div class=\"why-kurly\">\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"icon\">\r\n");
      out.write("                                                    <img src=\"../detailimg/check.png\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"info\">\r\n");
      out.write("                                                    <div class=\"title\">깐깐한 상품위원회</div>\r\n");
      out.write("                                                    <div class=\"desc\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            나와 내 가족이 먹고 쓸 상품을 고르는\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            마음으로 매주 상품을 직접 먹어보고,\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            경험해보고 성분, 맛, 안정성 등 다각도의\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            기준을 통과한 상품만을 판매합니다.\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"icon\">\r\n");
      out.write("                                                    <img src=\"../detailimg/only.png\" >\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"info\">\r\n");
      out.write("                                                    <div class=\"title\">차별화된 상품</div>\r\n");
      out.write("                                                    <div class=\"desc\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            전국 각지와 해외의 훌륭한 생산자가\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            믿고 선택하는 파트너, 마켓컬리.\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            2천여 개가 넘는 컬리 단독 브랜드, 스펙의\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            상품을 믿고 만나보세요.\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <span class=\"etc\">\r\n");
      out.write("                                                            (온라인 기준 / 자사몰, 직구 제외)\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"icon\">\r\n");
      out.write("                                                    <img src=\"../detailimg/truck.png\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"info\">\r\n");
      out.write("                                                    <div class=\"title\">신선한 풀콜드체인 배송</div>\r\n");
      out.write("                                                    <div class=\"desc\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            온라인 업계 최초로 산지에서 문 앞까지\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            상온, 냉장, 냉동 상품을 분리 포장 후\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            최적의 온도를 유지하는 냉장 배송 시스템,\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            풀콜드체인으로 상품을 신선하게 전해드립니다.\r\n");
      out.write("\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                        <span class=\"etc\">(샛별배송에 한함)</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"icon\">\r\n");
      out.write("                                                    <img src=\"../detailimg/price.png\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"info\">\r\n");
      out.write("                                                    <div class=\"title\">고객, 생산자를 위한 최선의 가격</div>\r\n");
      out.write("                                                    <div class=\"desc\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            매주 대형 마트와 주요 온라인 마트의 가격\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            변동 상황을 확인해 신선식품은 품질을\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            타협하지 않는 선에서 최선의 가격으로,\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            가공식품은 언제나 합리적인 가격으로\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            정기 조정합니다.\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"col\">\r\n");
      out.write("                                                <div class=\"icon\">\r\n");
      out.write("                                                    <img src=\"../detailimg/eco.png\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"info\">\r\n");
      out.write("                                                    <div class=\"title\">환경을 생각하는 지속 가능한 유통</div>\r\n");
      out.write("                                                    <div class=\"desc\">\r\n");
      out.write("                                                        <p>\r\n");
      out.write("                                                            친환경 포장재부터 생산자가 상품에만\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            집중할 수 있는 직매입 유통구조까지,\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            지속 가능한 유통을 고민하며 컬리를 있게\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            하는 모든 환경(생산자, 커뮤니티, 직원)이\r\n");
      out.write("                                                            <br>\r\n");
      out.write("                                                            더 나아질 수 있도록 노력합니다.\r\n");
      out.write("                                                        </p>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"happy_center fst\">\r\n");
      out.write("                                <div class=\"happy\">\r\n");
      out.write("                                    <h4 class=\"tit\">고객행복센터</h4>\r\n");
      out.write("                                    <p class=\"sub\">\r\n");
      out.write("                                        <span class=\"emph\">궁금하신 점이나 서비스 이용에 불편한 점이 있으신가요?</span>\r\n");
      out.write("                                        <span class=\"bar\"></span>\r\n");
      out.write("                                        문제가 되는 부분을 사진으로 찍어 아래 중 편하신 방법으로 접수해 주시면 빠르게 도와드리겠습니다.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <ul class=\"list\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div  >\r\n");
      out.write("                                        <b style=\"font-weight:bolder; color:#4B62D3; font-size:14pt;\">|</b>\r\n");
      out.write("                                            전화 문의 \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"sub\">오전 7시~오후 7시 (연중무휴)</div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li style=\"list-style: none;\">\r\n");
      out.write("                                        <div><b style=\"font-weight:bolder; color:#4B62D3; font-size:14pt;\" >|</b>\r\n");
      out.write("                                            카카오톡 문의\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"sub\">오전 7시~오후 7시 (연중무휴)</div>\r\n");
      out.write("                                        <div class=\"expend\" style=\"\">\r\n");
      out.write("                                            카카오톡에서 '새벽마켓'를 검색 후\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            대화창에 문의 및 불편사항을\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            남겨주세요\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li style=\"list-style: none;\">\r\n");
      out.write("                                        <div>\r\n");
      out.write("                                           <b style=\"font-weight:bolder; color:#4B62D3; font-size:14pt;\">|</b> 홈페이지 문의\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"sub\">\r\n");
      out.write("                                            24시간 접수 가능\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            로그인 > 새벽마켓 > 1:1문의\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"expend\">                                            \r\n");
      out.write("                                            고객센터 운영 시간에 순차적으로 답변해드리겠습니다.\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"happy_center order\">\r\n");
      out.write("                                <div class=\"happy unfold\">\r\n");
      out.write("                                    <h4 class=\"tit\">주문 취소 안내</h4>\r\n");
      out.write("                                    <ul class=\"sub\" style=\"list-style: none;\">\r\n");
      out.write("                                        <li >\r\n");
      out.write("                                            <strong class=\"emph\" >[입금 확인] 단계</strong>                                            \r\n");
      out.write("                                            마이컬리 > 주문 내역 상세페이지에서 직접 취소하실 수 있습니다.\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong class=\"emph\">[입금 확인] 이후 단계</strong>                                                                                        \r\n");
      out.write("                                            고객행복센터로 문의해주세요.\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <strong class=\"emph\">결제 승인 취소 / 환불</strong>                                                                                        \r\n");
      out.write("                                            결제 수단에 따라 영업일 기준 3~7일 내에 처리해드립니다.\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"happy_center lst\">\r\n");
      out.write("                                <div class=\"happy unfold\">\r\n");
      out.write("                                    <h4 class=\"tit\">교환 및 환불 안내</h4>\r\n");
      out.write("                                    <p class=\"sub\">\r\n");
      out.write("                                        고객님의 단순 변심으로 인한 반품은 어려울 수 있으니 양해 부탁드립니다.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <ul class=\"goods-view-infomation-tab-group\">\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-description\" class=\"goods-view-infomation-tab-anchor\">상품설명</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-infomation\" class=\"goods-view-infomation-tab-anchor\">상세정보</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"goods-view-infomation-tab\">\r\n");
      out.write("                                <a href=\"#goods-review\" class=\"goods-view-infomation-tab-anchor __active\">\r\n");
      out.write("                                    고객후기\r\n");
      out.write("                                    <span class=\"count_review\">(0)</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"goods-view-infomation-content\" id=\"goods-review\"> <!-- 아래 주소창에 good_review_list.html url 넣어주면 됩니당-->\r\n");
      out.write("                             <iframe src=\"../review/reviewList.jsp?item_num=");
      out.print(item_num );
      out.write("\" id=\"inreview\" frameborder=\"0\" class=\"goods-view-infomation-board\" height=\"4000\"></iframe>\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
