/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-24 01:08:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailAddrWindow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".delivery {\r\n");
      out.write("	color: #4B62D3;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	$(function() {\r\n");
      out.write("		$(\"#toggleBtn\").click(function() {\r\n");
      out.write("			$(\".text\").toggle();\r\n");
      out.write("		})\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div style=\"width: 100%\">\r\n");
      out.write("		<div style=\"width: 600px; margin: 0 auto;\">\r\n");
      out.write("			<div style=\"margin: 0 auto;\">\r\n");
      out.write("				<span class=\"delivery\">샛별배송</span> <span\r\n");
      out.write("					style=\"font-size: 30px; font-weight: bold;\">&nbsp;지역입니다.</span>\r\n");
      out.write("				<p style=\"font-size: 20px;\">매일 새벽,문 앞까지 신선함을 전해드려요.</p>\r\n");
      out.write("				<br> <br>\r\n");
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("				\r\n");
      out.write("					<div style=\"width:654px;\">\r\n");
      out.write("					<input type=\"text\" name=\"query\" placeholder=\"주소를 검색 해주세요\"\r\n");
      out.write("						style=\"width: 500px; height: 50px;\">\r\n");
      out.write("					<button type=\"submit\"\r\n");
      out.write("						style=\"width: 150px; height: 50px; color: #4B62D3; background-color: white\">\r\n");
      out.write("						<span class=\"glyphicon glyphicon-search\"></span>&nbsp;재검색\r\n");
      out.write("					</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<br> <br> <input type=\"text\" name=\"query\"\r\n");
      out.write("						placeholder=\"상세 주소를 입력하세요\" style=\"width: 654px; height: 50px;\"><br>\r\n");
      out.write("					<br>\r\n");
      out.write("					<p style=\"font-size: 7pt;\">*저장된 배송지는 최대7일간 임시 저장 후 자동 삭제됩니다.</p>\r\n");
      out.write("					<p style=\"font-size: 7pt;\">로그인 할 경우, 회원님의 배송지 목록에 추가됩니다.</p>\r\n");
      out.write("					<p>\r\n");
      out.write("						<button type=\"submit\"\r\n");
      out.write("							style=\"width: 654px; height: 50px; background-color: #4B62D3; color: white;\">저장</button>\r\n");
      out.write("					</p>\r\n");
      out.write("					<br> <br>\r\n");
      out.write("\r\n");
      out.write("					<span style=\"color: red; font-weight: bold;\">ⓘ샛별배송 지역 중 배송불가 장소 안내</span>\r\n");
      out.write("\r\n");
      out.write("					<div style=\"width: 600px;\">\r\n");
      out.write("\r\n");
      out.write("						<span style=\"float: left; width:60%; padding:1% 0 10% 0;\">관공서/학교/병원/시장/공단지역/산간지역/백화점 등</span>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"width: 35%; float: right;\">\r\n");
      out.write("							\r\n");
      out.write("								<button id=\"toggleBtn\" style = \"float:right;\">자세히보기</button>\r\n");
      out.write("						\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"clear: both\"></div>\r\n");
      out.write("\r\n");
      out.write("						<div style=\"text-align: left;\">\r\n");
      out.write("							<p class=\"text\">가락동농수산물도매시장</p>\r\n");
      out.write("							<p class=\"text\">가락동농수산물시장</p>\r\n");
      out.write("							<p class=\"text\">가천대학교</p>\r\n");
      out.write("							<p class=\"text\">고려대학교안암캠퍼스</p>\r\n");
      out.write("							<p class=\"text\">고매동 일부(일부지역만 배송가능)</p>\r\n");
      out.write("							<p class=\"text\">국립중앙박물관</p>\r\n");
      out.write("							<p class=\"text\">국민대학교</p>\r\n");
      out.write("							<p class=\"text\">덕성여자대학교</p>\r\n");
      out.write("							<p class=\"text\">덕양구 신원동 일부(일부지역만 배송가능)</p>\r\n");
      out.write("							<p class=\"text\">도내동 일부(원흥지구만 배송가능)</p>\r\n");
      out.write("							<p class=\"text\">동덕여자대학교</p>\r\n");
      out.write("							<p class=\"text\">반월특수지구</p>\r\n");
      out.write("							<p class=\"text\">서경대학교</p>\r\n");
      out.write("							<p class=\"text\">서울사이버대학교</p>\r\n");
      out.write("							<p class=\"text\">서울시립대학교</p>\r\n");
      out.write("							<p class=\"text\">서울여자대학교</p>\r\n");
      out.write("							<p class=\"text\">성균관대학교</p>\r\n");
      out.write("							<p class=\"text\">성신여자대학교</p>\r\n");
      out.write("							<p class=\"text\">세종대학교</p>\r\n");
      out.write("							<p class=\"text\">연세대학교</p>\r\n");
      out.write("							<p class=\"text\">이화여자대학교</p>\r\n");
      out.write("							<p class=\"text\">한국외국어대학교</p>\r\n");
      out.write("							<p class=\"text\">홍익대학교</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
