/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-10 09:15:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" media=\"all\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/footer.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	<div class=\"section inquiry\">\r\n");
      out.write("		<div class=\"secContents\">\r\n");
      out.write("			<h2>고객센터</h2>\r\n");
      out.write("			<div class=\"inquiryCon\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>전화문의 (1644 - 1107)</h4>\r\n");
      out.write("						<div class=\"line1\">\r\n");
      out.write("							<p class=\"day\">평일</p>\r\n");
      out.write("							<p class=\"serviceTime\"> 오전 7시 - 오후 6시</p>\r\n");
      out.write("							<p class=\"lunchtime\">(점심시간 낮 12시 - 오후 1시)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"line2\">\r\n");
      out.write("							<p class=\"day\">토요일, 일요일 &amp; 공휴일</p>\r\n");
      out.write("							<p class=\"serviceTime\"> 오전 8시 - 오후 12시</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>카카오톡 문의</h4>\r\n");
      out.write("						<div class=\"line1\">\r\n");
      out.write("							<p class=\"day\">평일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 4시</p>\r\n");
      out.write("							<p class=\"lunchtime\">(점심시간 오후 12시 - 오후 1시)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"line2\">\r\n");
      out.write("							<p class=\"day\">토요일, 일요일 &amp; 공휴일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 12시</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>1:1 문의 </h4>\r\n");
      out.write("						<p class=\"line1\">365일</p>\r\n");
      out.write("						<p>고객센터 운영시간에 순차적으로 답변드리겠습니다.</p>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"section last\">\r\n");
      out.write("		<div class=\"secContents\">\r\n");
      out.write("			<div class=\"lastLeft\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">컬리소개</a></li>\r\n");
      out.write("					<li><a href=\"#\">컬리영상소개</a></li>\r\n");
      out.write("					<li><a href=\"#\">이용안내</a></li>\r\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lastRight\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"img/instagram_logo.png\" alt=\"인스타그램\" onclick=\"window.open('https://www.instagram.com/marketkurly')\"/>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"img/facebook_logo.png\" alt=\"페이스북\" onclick=\"window.open('https://www.facebook.com/marketkurly')\"/>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<img src=\"img/blog_logo.png\" alt=\"블로그\" onclick=\"window.open('https://blog.naver.com/marketkurly')\"/>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"footerT\">\r\n");
      out.write("		<div class=\"fContents\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li>\r\n");
      out.write("					<p class=\"line1\">\r\n");
      out.write("						법인명 (상호) : 주식회사 컬리<br> 대표이사 : 김슬아 대표<br> 개인정보보호책임자 :\r\n");
      out.write("						이원준 <br>\r\n");
      out.write("					</p>\r\n");
      out.write("					<div class=\"n\">\r\n");
      out.write("						<p>사업자등록번호 :</p>\r\n");
      out.write("						<p class=\"n\">261-81-23567</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<p class=\"line1\">\r\n");
      out.write("						입점문의 : <a href=\"#\">입점문의하기</a><br> 마케팅제휴 : <a href=\"#\">marketing@kurlycorp.com</a><br>\r\n");
      out.write("						채용문의 : <a href=\"#\">recruit@kurlycorp.com</a><br> 팩스 : 02-3482-4636<br> \r\n");
      out.write("						주소 : 서울특별시 강남구 테헤란로 132(역삼동) 한독약품빌딩 8층 쌍용교육센터\r\n");
      out.write("					</p>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li><img src=\"img/saebyuk.png\" alt=\"로고\">\r\n");
      out.write("					<p>KURLY ALL RIGHT RESERVED</p></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
