/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-23 08:17:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.Dao.TimeSaleDao;
import data.Dto.itemDto;
import data.Dao.itemDao;
import java.util.List;
import data.Dao.TimeSaleDao;
import java.text.NumberFormat;
import java.util.Locale;
import data.Dto.TimeSaleDto;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.Dto.itemDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Locale");
    _jspx_imports_classes.add("data.Dao.itemDao");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("data.Dao.TimeSaleDao");
    _jspx_imports_classes.add("data.Dto.TimeSaleDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("  <title>Slide Project</title>\n");
      out.write("  \n");
      out.write("  <style>\n");
      out.write("  @import url('https://fonts.googleapis.com/css2?family=Gothic+A1&display=swap');\n");
      out.write("\n");
      out.write("    html, body { box-sizing: border-box; padding: 0; margin: 0; text-align: center;  min-height: 100vh; font-family: 'Gothic A1', sans-serif;}\n");
      out.write("    *, *:before, *:after { box-sizing: inherit; }\n");
      out.write("    .clearfix:after { content: ''; display: block; clear: both; float: none; }\n");
      out.write("    .title { margin-bottom: 0; text-align: center; font-size: 30px; color: #333; }\n");
      out.write("    .link, .link:visited { display: inline-block; margin: 20px 0; color: #555; text-decoration: none; font-weight: bold; }\n");
      out.write("    .link:hover, .link:focus { color: #9fd6c2; }\n");
      out.write("    /* container - body */\n");
      out.write("    #container { width: 100%; margin: auto; }\n");
      out.write("    .flex-slide{\n");
      out.write("    	width: 100%;\n");
      out.write("    	display:flex;\n");
      out.write("    	z-index:-1;\n");
      out.write("    }\n");
      out.write("    .slide_wrap { width: 1220px; padding-bottom: 40px;\n");
      out.write("     margin-left: 14.5%;}\n");
      out.write("    .slide_box { width: 1220px; margin:auto; overflow-x: hidden; text-align: center; }\n");
      out.write("    .slide_content { display: table; float: left; width: 305px; height: 300px;}\n");
      out.write("    \n");
      out.write("    .slide_btn_box {background:none; width:100%; height:100%; z-index:1; \n");
      out.write("     position: relative; top: -300px;}\n");
      out.write("    .slide_btn_box > button { position:relative; width: 60px; height: 60px; font-size: 16px;  background: none; border: 0px; cursor: pointer; }\n");
      out.write("    .slide_btn_box > .slide_btn_prev {left:-47%;}\n");
      out.write("    .slide_btn_box > .slide_btn_next {left:45%;}\n");
      out.write("    \n");
      out.write("    .slide_pagination { position: absolute; left: 50%; bottom: 0; list-style: none; margin: 0; padding: 0; transform: translateX(-50%); }\n");
      out.write("    .slide_pagination .dot { display: inline-block; width: 15px; height: 15px; margin: 0 5px; overflow: hidden; background: #ddd; border-radius: 50%; transition: 0.3s; }\n");
      out.write("    .slide_pagination .dot.dot_active { background: #333; }\n");
      out.write("    .slide_pagination .dot a { display: block; width: 100%; height: 100%; }\n");
      out.write("    \n");
      out.write("    .a{\n");
      out.write("  	text-decoration : none;\n");
      out.write("  	color:black;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<!-- 메인배너 -->\n");
      out.write("	.banner_container{\n");
      out.write("		width: 100%;\n");
      out.write("		display: flex;\n");
      out.write("		justify-content: center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.visual {\n");
      out.write("	\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.visual > .slide{\n");
      out.write("	    height: 370px;\n");
      out.write("	    /*margin-left: 300px;*/\n");
      out.write("	    margin-bottom: 40px;\n");
      out.write("	    width: 100%;\n");
      out.write("	    display: none;\n");
      out.write("	}\n");
      out.write("	.slide img{\n");
      out.write("		width:100%;\n");
      out.write("	}\n");
      out.write("	.visual > img {\n");
      out.write("	vertical-align: middle;\n");
      out.write("	\n");
      out.write("	}\n");
      out.write("	.visual > .slideshow-container {\n");
      out.write("	 \n");
      out.write("	  height: 500px;\n");
      out.write("	  /* margin-left:500px;\n");
      out.write("	  margin-right:500px; */\n");
      out.write("	 /*  margin:0 auto; */\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.visual > .slide.active {\n");
      out.write("	  opacity: 1;\n");
      out.write("	}\n");
      out.write("	/* GOODS */\n");
      out.write("	.goods{\n");
      out.write("	\n");
      out.write("	}\n");
      out.write("	.goods > .inner{\n");
      out.write("	   \n");
      out.write("	}\n");
      out.write("	.goods .goods-top{\n");
      out.write("	   text-align: center;\n");
      out.write("	   margin: 0 auto;\n");
      out.write("	    display: block;/* \n");
      out.write("	    justify-content: center; */\n");
      out.write("	    /* align-items: center; */\n");
      out.write("	    padding-top: 40px ;\n");
      out.write("	    margin-bottom: 27px;\n");
      out.write("	/*       margin-right:80px; */\n");
      out.write("	}\n");
      out.write("	.goods .goods-top span{\n");
      out.write("	    color: rgb(51, 51, 51);\n");
      out.write("	    font-size: 28px;\n");
      out.write("	    line-height: 1.15;\n");
      out.write("	    letter-spacing: -0.26px;\n");
      out.write("	    font-weight: 500;\n");
      out.write("	    padding: 8px 0;\n");
      out.write("	    margin-left: 10px;\n");
      out.write("	    margin-right: 50px;\n");
      out.write("	}\n");
      out.write("	.goods .goods-list{\n");
      out.write("	    display: flex;\n");
      out.write("	    justify-content: space-between;\n");
      out.write("	    padding-bottom: 40px;\n");
      out.write("	    float:left;\n");
      out.write("	    text-align:center;\n");
      out.write("	    margin-left: 500px;\n");
      out.write("	    margin-right: 500px;\n");
      out.write("	    }\n");
      out.write("	.goods .goods-list .goods-card{\n");
      out.write("	    margin-right: 18px;\n");
      out.write("	   \n");
      out.write("	}\n");
      out.write("	.goods .goods-list .goods-card .img-container{\n");
      out.write("	   \n");
      out.write("	    height: 320px;\n");
      out.write("	    position: relative;\n");
      out.write("	   \n");
      out.write("	    \n");
      out.write("	}\n");
      out.write("	.goods .goods-list .goods-card .img-container img{\n");
      out.write("	    height: 100%;\n");
      out.write("	    \n");
      out.write("	    \n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.fade {\n");
      out.write("	  -webkit-animation-name: fade;\n");
      out.write("	  -webkit-animation-duration: 1.5s;\n");
      out.write("	  animation-name: fade;\n");
      out.write("	  animation-duration: 2.0s;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	@-webkit-keyframes fade {\n");
      out.write("	  from {opacity: .1} \n");
      out.write("	  to {opacity: 2}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	@keyframes fade {\n");
      out.write("	  from {opacity: .2} \n");
      out.write("	  to {opacity: 1}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.main_1>h1{\n");
      out.write("	     text-align : center;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.product_list{\n");
      out.write("	   display: flex;\n");
      out.write("	   float:left;\n");
      out.write("	   text-align:center;\n");
      out.write("	    margin-left: 500px;\n");
      out.write("	    margin-right: 500px;\n");
      out.write("	\n");
      out.write("	     \n");
      out.write("	}\n");
      out.write("	.slider-nav {\n");
      out.write("	  position: absolute;\n");
      out.write("	  bottom: 10px;\n");
      out.write("	  left: 50%;\n");
      out.write("	  transform: translateX(-50%);\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.slider-nav button {\n");
      out.write("	  margin: 0 10px;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	.ban{\n");
      out.write("		margin-left: 10px;\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("    .timeSale-wrap {\n");
      out.write("        display: inline-flex;\n");
      out.write("    }\n");
      out.write("    .saleItem {\n");
      out.write("        margin-right: 18px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("  #the-final-countdown {\n");
      out.write("      font-family: 'Gothic A1', sans-serif;\n");
      out.write("      text-align: center;\n");
      out.write("      color: dimgrey;\n");
      out.write("      font-size: 3rem;\n");
      out.write("      display: inline-flex;\n");
      out.write("      height: 50%;\n");
      out.write("      width: 40%;\n");
      out.write("  }\n");
      out.write("	\n");
      out.write("  </style>\n");
      out.write("  \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("   $(function(){\n");
      out.write("      \n");
      out.write("      var slideIndex = 0;\n");
      out.write("      showSlides();\n");
      out.write("\n");
      out.write("      function showSlides() {\n");
      out.write("          var i;\n");
      out.write("          \n");
      out.write("          var slides = document.getElementsByClassName(\"slide\");\n");
      out.write("          for (i = 0; i < slides.length; i++) {\n");
      out.write("             slides[i].style.display = \"none\";  \n");
      out.write("          }\n");
      out.write("          slideIndex++;\n");
      out.write("          if (slideIndex > slides.length) {slideIndex = 1}\n");
      out.write("          slides[slideIndex-1].style.display = \"block\"; \n");
      out.write("          \n");
      out.write("          /*\n");
      out.write("          var slides = $(\".slide\");\n");
      out.write("          slides.each(function(i,ele){\n");
      out.write("        	  $(ele).hide();\n");
      out.write("          });\n");
      out.write("          slideIndex++;\n");
      out.write("          if (slideIndex > slides.length) {slideIndex = 1}\n");
      out.write("          slides.eq(slideIndex-1).fadeIn('fast');*/\n");
      out.write("          \n");
      out.write("          setTimeout(showSlides, 2000); // Change image every 2 seconds\n");
      out.write("      }\n");
      out.write("   });\n");
      out.write("\n");
      out.write("   function randSale() {\n");
      out.write("       var randSale=Math.floor(Math.random()*16)+10;\n");
      out.write("       return randSale;\n");
      out.write("   }\n");
      out.write("   setInterval(function time(){\n");
      out.write("       var d = new Date();\n");
      out.write("       var hours = 24 - d.getHours();\n");
      out.write("       var min = 60 - d.getMinutes();\n");
      out.write("       if((min + '').length == 1){\n");
      out.write("           min = '0' + min;\n");
      out.write("       }\n");
      out.write("       var sec = 60 - d.getSeconds();\n");
      out.write("       if((sec + '').length == 1){\n");
      out.write("           sec = '0' + sec;\n");
      out.write("       }\n");
      out.write("       jQuery('#the-final-countdown p').html(hours+':'+min+':'+sec)\n");
      out.write("   }, 1000);\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 메인배너 -->\n");
      out.write("	<div class=\"banner_container\">\n");
      out.write("   \n");
      out.write("    <section class=\"visual\">\n");
      out.write("    <div class = \"slideshow-container\">\n");
      out.write("        \n");
      out.write("        <div class=\"slide fade\">\n");
      out.write("        <a href = \"https://www.kurly.com/categories/825\">\n");
      out.write("        <img alt = \"\" src = \"image3/banner1.jpg\">\n");
      out.write("        </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"slide fade\">\n");
      out.write("        <a href = \"https://www.kurly.com/shop/main/html.php?htmid=event/kurly.htm&name=friend\">\n");
      out.write("        <img alt = \"\" src = \"image3/banner2.jpg\">\n");
      out.write("        </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"slide fade\">\n");
      out.write("        <a href = \"https://www.kurly.com/categories/139001\" >\n");
      out.write("        <img alt = \"\" src = \"image3/banner3.jpg\">\n");
      out.write("        </a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"slide fade\">\n");
      out.write("        <a href = \"https://www.kurly.com/categories/863\">\n");
      out.write("        <img alt = \"\" src = \"image3/banner4.jpg\">\n");
      out.write("        </a>\n");
      out.write("        </div>\n");
      out.write("   </div>\n");
      out.write("   </section>\n");
      out.write("   </div>\n");
      out.write("   \n");
      out.write("   <div>\n");
      out.write("   		<section>\n");
      out.write("			<div class = \"ban\">\n");
      out.write("				<img src = \"image3/그림1.jpg\" width = \"1300px;\">\n");
      out.write("			</div>   		\n");
      out.write("   		</section>	\n");
      out.write("   </div>\n");
      out.write("   <div>\n");
      out.write("   	<a href =\"#\"></a>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("  <!-- 네비게이터 -->\n");
      out.write("\n");
      out.write("  <h1 class=\"title\">이 상품 어때요 ?</h1>\n");
      out.write("  <a href=\"#\" class=\"link\" target=\"_blank\"></a>\n");
      out.write("  \n");
      out.write("  <div id=\"container\">\n");
      out.write("    <div class=\"slide_wrap slide1\">\n");
      out.write("   	<div class=\"flex-slide\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("       	");
 
       	int startNum = (int)((Math.random()*29)); // 0 ~ 28
    	
    	itemDao dao = new itemDao();
    	List<itemDto> list = dao.getList(startNum, 12);
    	
    	for(itemDto dto: list){
    		
       	
      out.write("\n");
      out.write("          <div class=\"slide_content slide01\">\n");
      out.write("              <a href = \"index.jsp?main=detail/detailView.jsp?item_num=");
      out.print(dto.getItem_num() );
      out.write("\" class = \"a\">\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\n");
      out.write("          	</a>\n");
      out.write("          </div>\n");
      out.write("         ");
 
    	}
          
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("     </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("      <!-- 특가 아이템 창 -->\n");
      out.write("        <div>\n");
      out.write("            <div>\n");
      out.write("            <h2>일일특가</h2>\n");
      out.write("            <h5 style=\"color: gray;\">24시간 한정 특가</h5>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div id=\"the-final-countdown\">\n");
      out.write("                <i class=\"fa-solid fa-clock\" style=\"color: #4c62d3; white-space: nowrap; margin-right: 10px;\"></i>\n");
      out.write("                <p></p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"timeSale-wrap\">\n");
      out.write("                ");

                    TimeSaleDao tdao=new TimeSaleDao();
                    List<String> random=tdao.randomItem();
                    NumberFormat nf=NumberFormat.getInstance(Locale.KOREA);

                    for(String arr:random) {
//                        System.out.println(arr);
                        itemDto idto=tdao.selectItem(arr);
                        int randomPercent=(int)(Math.floor(Math.random()*25)+10);
                        int price= dao.getItemPrice(arr)*(100-randomPercent)/100;
                        tdao.updateSalePrice(price,arr);
                
      out.write("\n");
      out.write("                <div class=\"saleItem\">\n");
      out.write("                    <img src=\"../save-info-img/");
      out.print(idto.getItem_img());
      out.write("\" width=\"300\">\n");
      out.write("                    <h5>");
      out.print(idto.getItem_name());
      out.write("</h5>\n");
      out.write("                    <h6>");
      out.print(randomPercent);
      out.write("%할인</h6>\n");
      out.write("                    <h4>");
      out.print(nf.format(tdao.getPrice(arr)));
      out.write("원</h4>\n");
      out.write("                </div>\n");
      out.write("                ");
 }  
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("   	<h2>카테고리별 상품 미리보기</h2>\n");
      out.write("    <h1 class=\"title\">육류</h1>\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\n");
      out.write("   	<div class=\"slide_wrap slide2\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("       	");
 
    	List<itemDto> list2 = dao.getListCategory("meat", 0, 8);
    	
    	for(itemDto dto: list2){
    		
       	
      out.write("\n");
      out.write("            <div class=\"slide_content slide01\">\n");
      out.write("                <a href = \"index.jsp?main=detail/detailView.jsp?item_num=");
      out.print(dto.getItem_num() );
      out.write("\" class = \"a\">\n");
      out.write("                    <img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\n");
      out.write("                    <p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\n");
      out.write("                    <p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("         ");
 
    	}
          
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("    <h1 class=\"title\">해산물</h1>\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\n");
      out.write("   	<div class=\"slide_wrap slide3\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("       	");
 
    	List<itemDto> list3 = dao.getListCategory("seafood", 0, 8);
    	
    	for(itemDto dto: list3){
    		
       	
      out.write("\n");
      out.write("          <div class=\"slide_content slide01\">\n");
      out.write("              <a href = \"index.jsp?main=detail/detailView.jsp?item_num=");
      out.print(dto.getItem_num() );
      out.write("\" class = \"a\">\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\n");
      out.write("          	</a>\n");
      out.write("          </div>\n");
      out.write("         ");
 
    	}
          
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("  <h1 class=\"title\">과일</h1>\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\n");
      out.write("   	<div class=\"slide_wrap slide4\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("       	");
 
    	List<itemDto> list4 = dao.getListCategory("fruit", 0, 8);
    	
    	for(itemDto dto: list4){
    		
       	
      out.write("\n");
      out.write("          <div class=\"slide_content slide01\">\n");
      out.write("              <a href = \"index.jsp?main=detail/detailView.jsp?item_num=");
      out.print(dto.getItem_num() );
      out.write("\" class = \"a\">\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\n");
      out.write("          	</a>\n");
      out.write("          </div>\n");
      out.write("         ");
 
    	}
          
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("  \n");
      out.write("  <h1 class=\"title\">베이커리</h1>\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\n");
      out.write("   	<div class=\"slide_wrap slide5\">\n");
      out.write("      <div class=\"slide_box\">\n");
      out.write("        <div class=\"slide_list clearfix\">\n");
      out.write("       	");
 
    	List<itemDto> list5 = dao.getListCategory("bakery", 0, 8);
    	
    	for(itemDto dto: list5){
    		
       	
      out.write("\n");
      out.write("          <div class=\"slide_content slide01\">\n");
      out.write("              <a href = \"index.jsp?main=detail/detailView.jsp?item_num=");
      out.print(dto.getItem_num() );
      out.write("\" class = \"a\">\n");
      out.write("              <img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\n");
      out.write("          	</a>\n");
      out.write("          </div>\n");
      out.write("         ");
 
    	}
          
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <!-- // .slide_list -->\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_box -->\n");
      out.write("      <div class=\"slide_btn_box\">\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\n");
      out.write("      </div>\n");
      out.write("      <!-- // .slide_btn_box -->\n");
      out.write("      <!-- // .slide_pagination -->\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("</div>\n");
      out.write("  <!-- // .container -->\n");
      out.write("\n");
      out.write("  <script> \n");
      out.write("  	slide('.slide1');\n");
      out.write("  	slide('.slide2');\n");
      out.write("  	slide('.slide3');\n");
      out.write("  	slide('.slide4');\n");
      out.write("  	slide('.slide5');\n");
      out.write("  	\n");
      out.write("    function slide(root_name) {\n");
      out.write("      const root = document.querySelector(root_name);\n");
      out.write("      const slideList = root.querySelector('.slide_list');  // Slide parent dom\n");
      out.write("      const slideContents = root.querySelectorAll('.slide_content');  // each slide dom\n");
      out.write("      const slideBtnNext = root.querySelector('.slide_btn_next'); // next button\n");
      out.write("      const slideBtnPrev = root.querySelector('.slide_btn_prev'); // prev button\n");
      out.write("      const slideLen = slideContents.length;  // slide length\n");
      out.write("      const slideWidth = 1220; // slide width\n");
      out.write("      const slideSpeed = 300; // slide speed\n");
      out.write("      const startNum = 0; // initial slide index (0 ~ 4)\n");
      out.write("      \n");
      out.write("      slideList.style.width = slideWidth * (slideLen + 2) + \"px\";\n");
      out.write("      \n");
      out.write("      // Copy first and last slide\n");
      out.write("      let firstChild = slideList.firstElementChild;\n");
      out.write("      let lastChild = slideList.lastElementChild;\n");
      out.write("      let clonedFirst = firstChild.cloneNode(true);\n");
      out.write("      let clonedLast = lastChild.cloneNode(true);\n");
      out.write("\n");
      out.write("      // Add copied Slides\n");
      out.write("      slideList.appendChild(clonedFirst);\n");
      out.write("      slideList.insertBefore(clonedLast, slideList.firstElementChild);\n");
      out.write("\n");
      out.write("      // Add pagination dynamically\n");
      out.write("\n");
      out.write("      slideList.style.transform = \"translate3d(-\" + (slideWidth)*0 + \"px, 0px, 0px)\";\n");
      out.write("\n");
      out.write("      let curIndex = startNum; // current slide index (except copied slide)\n");
      out.write("      let curSlide = slideContents[curIndex]; // current slide dom\n");
      out.write("      \n");
      out.write("      var next=0;\n");
      out.write("\n");
      out.write("      /** Next Button Event */\n");
      out.write("      slideBtnNext.addEventListener('click', function() {\n");
      out.write("        if (curIndex < slideLen-4) {\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + (slideWidth * (next + 1)) + \"px, 0px, 0px)\";\n");
      out.write("\n");
      out.write("          if(curIndex<0){\n");
      out.write("        	  curIndex=0;\n");
      out.write("          }\n");
      out.write("          curIndex=curIndex+4;\n");
      out.write("          next=next+1;\n");
      out.write("          console.log(curIndex);\n");
      out.write("        }\n");
      out.write("        else if (curIndex >= slideLen-4) {\n");
      out.write("          setTimeout(function() {\n");
      out.write("            slideList.style.transition = \"1000ms\";\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + (slideWidth)*0 + \"px, 0px, 0px)\";\n");
      out.write("          }, slideSpeed);\n");
      out.write("          curIndex = 0;\n");
      out.write("          next=0;\n");
      out.write("          console.log(curIndex);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        curSlide = slideContents[curIndex];\n");
      out.write("      });\n");
      out.write("\n");
      out.write("      /** Prev Button Event */\n");
      out.write("      slideBtnPrev.addEventListener('click', function() {\n");
      out.write("        if (curIndex > 0) {\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + slideWidth*(next-1) + \"px, 0px, 0px)\";\n");
      out.write("          \n");
      out.write("          curIndex=curIndex-4;\n");
      out.write("          \n");
      out.write("          next=next-1;\n");
      out.write("          \n");
      out.write("          console.log(curIndex);\n");
      out.write("        }\n");
      out.write("        else if (curIndex <= 0) {\n");
      out.write("          setTimeout(function() {\n");
      out.write("            slideList.style.transition = \"1000ms\";\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + slideWidth*(slideLen/4-1) + \"px, 0px, 0px)\";\n");
      out.write("          }, slideSpeed);\n");
      out.write("          curIndex = slideLen-4;\n");
      out.write("          next= slideLen/4-1;\n");
      out.write("          console.log(curIndex);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        curSlide = slideContents[curIndex];\n");
      out.write("      });\n");
      out.write("\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
