/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-16 01:31:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dao.MemberDao;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.MemberDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	div.join_container{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	form.join_form{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		width: 670px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.join_title>div{\r\n");
      out.write("		text-align: right;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		font-size: 9pt;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.join_title>h2{\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		margin-bottom: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#join_info{\r\n");
      out.write("		border-top: 2px solid black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#join_info>div{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	span.req_mark{\r\n");
      out.write("		color: red;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_title{\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		padding: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_input{\r\n");
      out.write("		width: 350px;\r\n");
      out.write("		padding: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_input>input{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 46px;\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("		border: 1px solid lightgray;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_input>input:focus{\r\n");
      out.write("		border: 1px solid gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_btn{\r\n");
      out.write("		width: 140px;\r\n");
      out.write("		padding: 10px 10px 10px 0px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_btn>button{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 46px;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		font-size: 11pt;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		color: #4B62D3;\r\n");
      out.write("		border: 1px solid #4B62D3;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#addr_find{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 46px;\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("		background-color: white;\r\n");
      out.write("		font-size: 11pt;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		color: #4B62D3;\r\n");
      out.write("		border: 1px solid #4B62D3;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.info_div>div{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.nextline{\r\n");
      out.write("		clear: both;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#birth_div{\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		height: 46px;\r\n");
      out.write("		padding: 15px 15px 15px 80px;\r\n");
      out.write("		border: 1px solid lightgray;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#birth_div>div{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#birth_div input{\r\n");
      out.write("		margin: 0 auto;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		border-width: 0px;\r\n");
      out.write("		width: 50px;\r\n");
      out.write("		outline: none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#agree_info{\r\n");
      out.write("		margin-top: 30px;\r\n");
      out.write("		border-top: 1px solid black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#agree_title{\r\n");
      out.write("		width: 150px;\r\n");
      out.write("		padding: 25px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.agree_sub{\r\n");
      out.write("		width: 520px;\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#agree_info>div{\r\n");
      out.write("		float: left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.sub_deatail{\r\n");
      out.write("		margin-left: 13px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.sub_deatail>h5{\r\n");
      out.write("		float: left;\r\n");
      out.write("		margin-right: 60px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	span.req_gray{\r\n");
      out.write("		color:lightgray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#join_btn{\r\n");
      out.write("		margin-top: 40px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#submit_btn{\r\n");
      out.write("		color: white;\r\n");
      out.write("		background-color: #4B62D3;\r\n");
      out.write("		border: 1px solid #4B62D3;\r\n");
      out.write("		width: 35%;\r\n");
      out.write("		height: 55px;\r\n");
      out.write("		border-radius: 5px;\r\n");
      out.write("		font-size: 11pt;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/*체크박스모양 바꾸기*/\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	input[type=\"checkbox\"] {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    display:none;\r\n");
      out.write("	    appearance: none;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"] {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    display: inline-block;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	    width: 25px;\r\n");
      out.write("	    height: 25px;\r\n");
      out.write("	\r\n");
      out.write("		margin: -2px 10px 0 0;\r\n");
      out.write("	\r\n");
      out.write("	    vertical-align: middle;\r\n");
      out.write("	\r\n");
      out.write("	    background-size: cover;\r\n");
      out.write("	    \r\n");
      out.write("	    background: url(../imgsource/checkbox_default.png) no-repeat;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"]:checked {\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	     background-size: cover;\r\n");
      out.write("	     \r\n");
      out.write("	     background: url(../imgsource/checkbox_checked.png) no-repeat;\r\n");
      out.write("	     \r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"]:focus {\r\n");
      out.write("		outline:none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");


MemberDao dao=new MemberDao();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	idCheck=false;\r\n");
      out.write("	emailCheck=false;\r\n");
      out.write("	\r\n");
      out.write("	$(\".addr_show\").hide();\r\n");
      out.write("	\r\n");
      out.write("	//회원가입 버튼을 눌렀을 때 주소를 입력 안했다면 주소를 입력하게 한다\r\n");
      out.write("	$(\"#submit_btn\").click(function(){\r\n");
      out.write("		//hide상태라면\r\n");
      out.write("		if($(\"#pass\").val()==\"\"){\r\n");
      out.write("			alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("		}else if($(\"#pass_check\").val()==\"\"){\r\n");
      out.write("			alert(\"비밀번호를 확인해주세요.\");\r\n");
      out.write("		}else if($(\"#name\").val()==\"\"){\r\n");
      out.write("			alert(\"이름을 입력해주세요.\");\r\n");
      out.write("		}else if($(\"#email\").val()==\"\"){\r\n");
      out.write("			alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("		}else if($(\"#hp\").val()==\"\"){\r\n");
      out.write("			alert(\"휴대폰 번호를 입력해주세요.\");\r\n");
      out.write("		}else if($(\".addr_show\").is(\":visible\")==false){\r\n");
      out.write("			alert(\"주소를 입력해주세요.\");\r\n");
      out.write("		//아이디 중복체크를 안했다면\r\n");
      out.write("		}else if(idCheck==false){\r\n");
      out.write("			alert(\"아이디 중복체크를 해주세요.\");\r\n");
      out.write("		}else if(emailCheck==false){\r\n");
      out.write("			alert(\"이메일 중복체크를 해주세요.\");\r\n");
      out.write("		}else if($(\"#pass\").val()!=$(\"#pass_check\").val()){\r\n");
      out.write("			alert(\"비밀번호를 잘못 입력했습니다.\");\r\n");
      out.write("			$(\"#pass\").val(\"\");\r\n");
      out.write("			$(\"#pass_check\").val(\"\");\r\n");
      out.write("		}else{\r\n");
      out.write("\r\n");
      out.write("			var year=$(\"#year\").val();\r\n");
      out.write("			var month=$(\"#month\").val();\r\n");
      out.write("			var day=$(\"#day\").val();\r\n");
      out.write("			\r\n");
      out.write("			if(year==\"\" && month==\"\" && day==\"\"){\r\n");
      out.write("				\r\n");
      out.write("			}else{\r\n");
      out.write("				\r\n");
      out.write("				var birth=year+\"/\"+month+\"/\"+day;\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:\"get\",\r\n");
      out.write("					dataType:\"json\",\r\n");
      out.write("					url:\"birthCheck.jsp\",\r\n");
      out.write("					data:{\"birth\":birth,\"year\":year,\"month\":month,\"day\":day},\r\n");
      out.write("					success:function(res){\r\n");
      out.write("						if(res.isbirth==2){\r\n");
      out.write("							alert(\"만 14세 이상만 가입이 가능합니다.\");\r\n");
      out.write("							$(\"#year\").val(\"\");\r\n");
      out.write("							$(\"#month\").val(\"\");\r\n");
      out.write("							$(\"#day\").val(\"\");\r\n");
      out.write("							return;\r\n");
      out.write("						}else if(res.isbirth==0){\r\n");
      out.write("							alert(\"올바른 생년월일을 입력해주세요.\");\r\n");
      out.write("							$(\"#year\").val(\"\");\r\n");
      out.write("							$(\"#month\").val(\"\");\r\n");
      out.write("							$(\"#day\").val(\"\");\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if($(\"#req_check1\").is(\":checked\")==false||$(\"#req_check2\").is(\":checked\")==false||$(\"#req_check3\").is(\":checked\")==false){\r\n");
      out.write("				alert(\"필수 항목을 체크해주세요.\")\r\n");
      out.write("				return;\r\n");
      out.write("			}else{\r\n");
      out.write("				//location.href=\"joinAction.jsp\";\r\n");
      out.write("				var data=$(\".join_form\").serialize();\r\n");
      out.write("				//alert(data);\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type:\"post\",\r\n");
      out.write("					dataType:\"html\",\r\n");
      out.write("					url:\"joinAction.jsp\",\r\n");
      out.write("					data:data,\r\n");
      out.write("					success:function(res){\r\n");
      out.write("						alert(\"회원가입을 환영합니다!\")\r\n");
      out.write("						location.href=\"loginForm.jsp\";\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이용약관 전체 선택 버튼\r\n");
      out.write("	$(\"#agreeAll\").click(function(){\r\n");
      out.write("		if($(this).is(\":checked\")){\r\n");
      out.write("			$(\".sub_content input\").prop('checked',true);\r\n");
      out.write("		}else{\r\n");
      out.write("			$(\".sub_content input\").prop('checked',false);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//아이디 중복 체크\r\n");
      out.write("	$(\"#id_check\").click(function(){\r\n");
      out.write("		var id=$(\"#id\").val().trim();\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			url:\"idCheck.jsp\",\r\n");
      out.write("			data:{\"id\":id},\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				//아이디가 중복됐다면\r\n");
      out.write("				if(res.idok>0){\r\n");
      out.write("					$(\"#id_retry\").html(\"<br>중복 아이디입니다.\");\r\n");
      out.write("					$(\"#id\").val(\"\");\r\n");
      out.write("					idCheck=false;\r\n");
      out.write("				}else if(id==\"\"){\r\n");
      out.write("					$(\"#id_retry\").html(\"<br>아이디를 입력하세요.\");\r\n");
      out.write("					idCheck=false;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#id_retry\").html(\"<br>사용 가능한 아이디입니다.\");\r\n");
      out.write("					idCheck=true;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//이메일 중복 체크\r\n");
      out.write("	$(\"#email_check\").click(function(){\r\n");
      out.write("		var email=$(\"#email\").val().trim();\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			url:\"emailCheck.jsp\",\r\n");
      out.write("			data:{\"email\":email},\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				//이메일이 중복됐다면\r\n");
      out.write("				if(res.emailok>0){\r\n");
      out.write("					$(\"#email_retry\").html(\"<br>중복 이메일입니다.\");\r\n");
      out.write("					$(\"#email\").val(\"\");\r\n");
      out.write("					emailCheck=false;\r\n");
      out.write("				}else if(email==\"\"){\r\n");
      out.write("					$(\"#email_retry\").html(\"<br>이메일을 입력하세요.\");\r\n");
      out.write("					emailCheck=false;\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#email_retry\").html(\"<br>사용 가능한 이메일입니다.\");\r\n");
      out.write("					emailCheck=true;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//아이디란을 바꾸면 아이디 중복 검사를 다시 실행\r\n");
      out.write("	$(\"#id\").change(function(){\r\n");
      out.write("		$(\"#id_retry\").html(\"\");\r\n");
      out.write("		idCheck=false;\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	//이메일란을 바꾸면 아이디 중복 검사를 다시 실행\r\n");
      out.write("	$(\"#email\").change(function(){\r\n");
      out.write("		$(\"#email_retry\").html(\"\");\r\n");
      out.write("		emailCheck=false;\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//주소찾기 api\r\n");
      out.write("function sample6_execDaumPostcode() {\r\n");
      out.write("    new daum.Postcode({\r\n");
      out.write("        oncomplete: function(data) {\r\n");
      out.write("            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("            // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("            var addr = ''; // 주소 변수\r\n");
      out.write("            var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("            //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("            if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                addr = data.roadAddress;\r\n");
      out.write("            } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                addr = data.jibunAddress;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("            if(data.userSelectedType === 'R'){\r\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                    extraAddr += data.bname;\r\n");
      out.write("                }\r\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                }\r\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                if(extraAddr !== ''){\r\n");
      out.write("                    extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                }\r\n");
      out.write("            \r\n");
      out.write("            } else {\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("            document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("            // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("            document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            \r\n");
      out.write("            //주소 검색 버튼을 숨기고 입력한 주소창을 보여준다.\r\n");
      out.write("            $(\"#addr_find\").hide();\r\n");
      out.write("            $(\".addr_show\").show();\r\n");
      out.write("        }\r\n");
      out.write("    }).open();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"join_container\">\r\n");
      out.write("		<form action=\"\" method=\"post\" class=\"join_form\">\r\n");
      out.write("			<div class=\"join_title\">\r\n");
      out.write("				<h2><b>회원가입</b></h2>\r\n");
      out.write("				<div>\r\n");
      out.write("					<span class=\"req_mark\">*</span>\r\n");
      out.write("					<span>필수입력사항</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 정보 입력창 -->\r\n");
      out.write("			<div id=\"join_info\">\r\n");
      out.write("	\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>아이디<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"text\" name=\"id\" placeholder=\"아이디를 입력해주세요\" \r\n");
      out.write("						required=\"required\" id=\"id\">\r\n");
      out.write("						<span style=\"font-size: 8pt;\" id=\"id_retry\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_btn\">\r\n");
      out.write("						<button type=\"button\" id=\"id_check\">중복확인</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>비밀번호<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"password\" name=\"pass\" placeholder=\"비밀번호를 입력해주세요\" \r\n");
      out.write("						required=\"required\" id=\"pass\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>비밀번호확인<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"password\"\" name=\"pass_check\" placeholder=\"비밀번호를 한번 더 입력해주세요\" \r\n");
      out.write("						required=\"required\" id=\"pass_check\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>이름<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"text\" name=\"name\" placeholder=\"이름을 입력해주세요\" id=\"name\"\r\n");
      out.write("						required=\"required\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>이메일<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"email\" name=\"email\" placeholder=\"예: dawnmarket@dawn.com\" \r\n");
      out.write("						required=\"required\" id=\"email\">\r\n");
      out.write("						<span style=\"font-size: 8pt;\" id=\"email_retry\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_btn\">\r\n");
      out.write("						<button type=\"button\" id=\"email_check\">중복확인</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>휴대폰<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<input type=\"text\" name=\"hp\" placeholder=\"예: 숫자만 입력해주세요\"  id=\"hp\"\r\n");
      out.write("						required=\"required\" pattern=\"[0-9]+\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_btn\">\r\n");
      out.write("						<button type=\"button\" id=\"hp_check\">인증번호 받기</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>주소<span class=\"req_mark\">*</span></b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<button type=\"button\" id=\"addr_find\" onclick=\"sample6_execDaumPostcode()\">\r\n");
      out.write("						<span class=\"glyphicon glyphicon-search\"></span>주소 검색</button>\r\n");
      out.write("						\r\n");
      out.write("						<input type=\"text\" name=\"addr1\" placeholder=\"메인주소\" \r\n");
      out.write("						style=\"margin-bottom: 10px;\" class=\"addr_show\" \r\n");
      out.write("						id=\"sample6_address\">\r\n");
      out.write("						<input type=\"text\" name=\"addr2\" placeholder=\"상세주소\" class=\"addr_show\" \r\n");
      out.write("						id=\"sample6_detailAddress\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_btn\">\r\n");
      out.write("						<button type=\"button\" id=\"hp_check\" class=\"addr_show\" \r\n");
      out.write("						onclick=\"sample6_execDaumPostcode()\">재검색</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"info_div\">\r\n");
      out.write("					<div class=\"info_title\">\r\n");
      out.write("						<b>생년월일</b>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"info_input\">\r\n");
      out.write("						<div id=\"birth_div\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"year\" placeholder=\"YYYY\" \r\n");
      out.write("								pattern=\"^[0-9]{4,4}$\" id=\"year\">\r\n");
      out.write("								<span>/</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"month\" placeholder=\"MM\" \r\n");
      out.write("								pattern=\"^[0-9]{2,2}$\" id=\"month\">\r\n");
      out.write("								<span>/</span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"text\" name=\"day\" placeholder=\"DD\" \r\n");
      out.write("								pattern=\"^[0-9{2,2}]$\" id=\"day\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"nextline\"></div>\r\n");
      out.write("				\r\n");
      out.write("			<!-- 동의창 -->\r\n");
      out.write("			<div id=\"agree_info\">\r\n");
      out.write("				<div id=\"agree_title\">\r\n");
      out.write("					<b>이용약관동의<span class=\"req_mark\">*</span></b>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"agree_sub\">\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h4><input type=\"checkbox\" id=\"agreeAll\">&nbsp;<b>전체 동의합니다.</b></h4>\r\n");
      out.write("						<div class=\"sub_deatail\">\r\n");
      out.write("							<h6>선택항목에 동의하지 않는 경우도 회원가입 및 일반적인 서비스를 이용할 수 있습니다.</h6>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h5><input type=\"checkbox\" id=\"req_check1\"\r\n");
      out.write("						required=\"required\">&nbsp;이용약관 동의&nbsp;<span class=\"req_gray\">(필수)</span></h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h5><input type=\"checkbox\" id=\"req_check2\"\r\n");
      out.write("						required=\"required\">&nbsp;개인정보 수집·이용 동의&nbsp;<span class=\"req_gray\">(필수)</span></h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h5><input type=\"checkbox\">&nbsp;개인정보 수집·이용 동의&nbsp;<span class=\"req_gray\">(선택)</span></h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h5><input type=\"checkbox\">&nbsp;무료배송, 할인쿠폰 등 혜택/정보 수신 동의&nbsp;<span class=\"req_gray\">(선택)</span></h5>\r\n");
      out.write("						<div class=\"sub_deatail\">\r\n");
      out.write("							<h5><input type=\"checkbox\">&nbsp;SMS</h5>\r\n");
      out.write("							<h5><input type=\"checkbox\">&nbsp;이메일</h5>\r\n");
      out.write("							<div class=\"nextline\"></div>\r\n");
      out.write("							<h6 style=\"color: #4B62D3; margin-left: 20px\"><span class=\"req_gray\">└</span>&nbsp;동의 시 한 달간[5%적립]+[2만원 이상 무료배송]첫 주문 후 안내</h6>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"sub_content\">\r\n");
      out.write("						<h5><input type=\"checkbox\" id=\"req_check3\"\r\n");
      out.write("						required=\"required\">&nbsp;본인은 만 14세 이상입니다.&nbsp;<span class=\"req_gray\">(필수)</span></h5>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"nextline\"></div>\r\n");
      out.write("							\r\n");
      out.write("			<div id=\"join_btn\">\r\n");
      out.write("				<button type=\"button\" id=\"submit_btn\">가입하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
