/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-28 03:45:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.3.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("	.lastRight>ul>li>img{\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.lastLeft>ul>li{\r\n");
      out.write("		float:left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<hr class=\"footer-hr\">\r\n");
      out.write("	<footer class=\"container\">\r\n");
      out.write("		<div class=\"row footer-border\">\r\n");
      out.write("			<div class=\"col-md-6 pull-left\" style = \"text-align:left;\">\r\n");
      out.write("				<h1 class=\"panel-title\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;고객행복센터</h1>\r\n");
      out.write("				<div class=\"footer1\">\r\n");
      out.write("				<ul style=\"list-style: none;\">\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>전화문의 (1644 - 1607)</h4>\r\n");
      out.write("						<div class=\"line1\">\r\n");
      out.write("							<p class=\"day\">평일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 4시</p>\r\n");
      out.write("							<p class=\"lunchtime\">(점심시간 오후 12시 - 오후 1시)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"line2\">\r\n");
      out.write("							<p class=\"day\">토요일, 일요일 &amp; 공휴일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 12시</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>카카오톡 문의</h4>\r\n");
      out.write("						<div class=\"line1\">\r\n");
      out.write("							<p class=\"day\">평일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 4시</p>\r\n");
      out.write("							<p class=\"lunchtime\">(점심시간 오후 12시 - 오후 1시)</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"line2\">\r\n");
      out.write("							<p class=\"day\">토요일, 일요일 &amp; 공휴일</p>\r\n");
      out.write("							<p class=\"serviceTime\">오전 8시 - 오후 12시</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<h4>1:1 문의</h4>\r\n");
      out.write("						<p class=\"line1\">궁금한 점이 있으신가요?</p>\r\n");
      out.write("						<p>1:1 문의에 남겨주시면 친절히 답변 드리겠습니다.</p>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-6 pull-right\" style = \"text-align:left;\">\r\n");
      out.write("			<div class=\"lastLeft\">\r\n");
      out.write("				<ul style=\"list-style: none;\">\r\n");
      out.write("					<li><a href=\"#\">컬리소개 &nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("					<li><a href=\"#\">컬리영상소개 &nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("					<li><a href=\"#\">이용안내 &nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("					<li><a href=\"#\">이용약관 &nbsp;&nbsp;&nbsp;&nbsp;</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("					<br><br>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lastRight\">\r\n");
      out.write("				<h5>법인명(상호) : 주식회사 새벽마켓 &nbsp;| &nbsp;사업자등록번호 : 아직 사업자 등록을 못했습니다</h5>\r\n");
      out.write("				<h5>통신판매업 : 제 2023-서울강남-0000호&nbsp;| &nbsp; 개인정보보호책임자:이지영</h5>\r\n");
      out.write("				<h5>주소 : 서울시 강남구 역삼동 쌍용교육센터 8층&nbsp;| &nbsp;대표이사 : 권예지</h5>\r\n");
      out.write("				<h5>입점문의 : 입점문의하기&nbsp;| &nbsp;제휴문의 :gns3967@naver.com</h5>\r\n");
      out.write("				<h5>채용문의 : recruit@saebyuk.com</h5>\r\n");
      out.write("				<br><br>\r\n");
      out.write("				<br><br><br>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"image/instagram_logo.png\" alt=\"인스타그램\" width = \"50\"\r\n");
      out.write("				onclick=\"window.open('https://www.instagram.com/marketkurly')\" />\r\n");
      out.write("						\r\n");
      out.write("				<img src=\"image/facebook_logo.png\" alt=\"페이스북\" width = \"50\"\r\n");
      out.write("				onclick=\"window.open('https://www.facebook.com/marketkurly')\"/> \r\n");
      out.write("					\r\n");
      out.write("				<img src=\"image/blog_logo.png\" alt=\"블로그\" width = \"50\" \r\n");
      out.write("				onclick=\"window.open('https://blog.naver.com/marketkurly')\"/>\r\n");
      out.write("				<br><br>\r\n");
      out.write("					\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style = \"text-align:right;\">\r\n");
      out.write("			<p>제작자</p>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<p>권예지 | 이지영 | 김병훈 | 서동익</p>\r\n");
      out.write("				</ul>\r\n");
      out.write("				\r\n");
      out.write("				<img src=\"image/saebyuk.png\" alt=\"로고\" width = \"200\">\r\n");
      out.write("					<p>ALL RIGHT RESERVED</p></div>\r\n");
      out.write("					<br><br><br><br>\r\n");
      out.write("					\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
