/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-03-16 09:27:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import data.dto.ItemDto;
import java.util.List;
import data.dao.ItemDao;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dto.ItemDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.json.simple.JSONObject");
    _jspx_imports_classes.add("data.dao.ItemDao");
    _jspx_imports_classes.add("org.json.simple.JSONArray");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>Slide Project</title>\r\n");
      out.write("  \r\n");
      out.write("  <style>\r\n");
      out.write("    html, body { box-sizing: border-box; padding: 0; margin: 0; text-align: center; }\r\n");
      out.write("    *, *:before, *:after { box-sizing: inherit; }\r\n");
      out.write("    .clearfix:after { content: ''; display: block; clear: both; float: none; }\r\n");
      out.write("    .title { margin-bottom: 0; text-align: center; font-size: 30px; color: #333; }\r\n");
      out.write("    .link, .link:visited { display: inline-block; margin: 20px 0; color: #555; text-decoration: none; font-weight: bold; }\r\n");
      out.write("    .link:hover, .link:focus { color: #9fd6c2; }\r\n");
      out.write("    /* container - body */\r\n");
      out.write("    #container { width: 1300px; margin: auto; }\r\n");
      out.write("    .slide_wrap { position: relative; width: 1220px; margin:0 auto; padding-bottom: 30px;}\r\n");
      out.write("    .slide_box { width: 100%; margin:auto; overflow-x: hidden; text-align: center;}\r\n");
      out.write("    .slide_content { display: table; float: left; width: 305px; height: 300px;}\r\n");
      out.write("    \r\n");
      out.write("    .slide_btn_box > button { position: absolute; top: 50%; margin-top: -45px; width: 60px; height: 60px; font-size: 16px;  background: none; border: 0px; cursor: pointer; }\r\n");
      out.write("    .slide_btn_box > .slide_btn_prev { top:190px; left: -30px; }\r\n");
      out.write("    .slide_btn_box > .slide_btn_next { top:190px; right: -10px; }\r\n");
      out.write("    \r\n");
      out.write("    .slide_pagination { position: absolute; left: 50%; bottom: 0; list-style: none; margin: 0; padding: 0; transform: translateX(-50%); }\r\n");
      out.write("    .slide_pagination .dot { display: inline-block; width: 15px; height: 15px; margin: 0 5px; overflow: hidden; background: #ddd; border-radius: 50%; transition: 0.3s; }\r\n");
      out.write("    .slide_pagination .dot.dot_active { background: #333; }\r\n");
      out.write("    .slide_pagination .dot a { display: block; width: 100%; height: 100%; }\r\n");
      out.write("    \r\n");
      out.write("    .a{\r\n");
      out.write("  	text-decoration : none;\r\n");
      out.write("  	color:black;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <h1 class=\"title\">이 상품 어때요 ?</h1>\r\n");
      out.write("  <a href=\"#\" class=\"link\" target=\"_blank\"></a>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("    <div class=\"slide_wrap slide1\">\r\n");
      out.write("      <div class=\"slide_box\">\r\n");
      out.write("        <div class=\"slide_list clearfix\">\r\n");
      out.write("       	");
 
       	int startNum = (int)((Math.random()*29)); // 0 ~ 28
    	
    	ItemDao dao = new ItemDao();
    	List<ItemDto> list = dao.getList(startNum, 12);
    	
    	for(ItemDto dto: list){
    		
       	
      out.write("\r\n");
      out.write("          <div class=\"slide_content slide01\">\r\n");
      out.write("          	<a href = \"#\" class = \"a\">\r\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\r\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\r\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\r\n");
      out.write("          	</a>\r\n");
      out.write("          </div>\r\n");
      out.write("         ");
 
    	}
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // .slide_list -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_box -->\r\n");
      out.write("      <div class=\"slide_btn_box\">\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_btn_box -->\r\n");
      out.write("      <!-- // .slide_pagination -->\r\n");
      out.write("    </div>\r\n");
      out.write("   	<h2>카테고리별 상품 미리보기</h2>\r\n");
      out.write("    <h1 class=\"title\">육류</h1>\r\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\r\n");
      out.write("   	<div class=\"slide_wrap slide2\">\r\n");
      out.write("      <div class=\"slide_box\">\r\n");
      out.write("        <div class=\"slide_list clearfix\">\r\n");
      out.write("       	");
 
    	ItemDao dao2 = new ItemDao();
    	List<ItemDto> list2 = dao.getListCategory("meat", 0, 8);
    	
    	for(ItemDto dto: list2){
    		
       	
      out.write("\r\n");
      out.write("          <div class=\"slide_content slide01\">\r\n");
      out.write("          	<a href = \"#\" class = \"a\">\r\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\r\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\r\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price());
      out.write("원</p>\r\n");
      out.write("          	</a>\r\n");
      out.write("          </div>\r\n");
      out.write("         ");
 
    	}
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // .slide_list -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_box -->\r\n");
      out.write("      <div class=\"slide_btn_box\">\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_btn_box -->\r\n");
      out.write("      <!-- // .slide_pagination -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- // .container -->\r\n");
      out.write("  \r\n");
      out.write("    <h1 class=\"title\">해산물</h1>\r\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\r\n");
      out.write("   	<div class=\"slide_wrap slide3\">\r\n");
      out.write("      <div class=\"slide_box\">\r\n");
      out.write("        <div class=\"slide_list clearfix\">\r\n");
      out.write("       	");
 
    	ItemDao dao3 = new ItemDao();
    	List<ItemDto> list3 = dao.getListCategory("seafood", 0, 8);
    	
    	for(ItemDto dto: list3){
    		
       	
      out.write("\r\n");
      out.write("          <div class=\"slide_content slide01\">\r\n");
      out.write("          	<a href = \"#\" class = \"a\">\r\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\r\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\r\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\r\n");
      out.write("          	</a>\r\n");
      out.write("          </div>\r\n");
      out.write("         ");
 
    	}
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // .slide_list -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_box -->\r\n");
      out.write("      <div class=\"slide_btn_box\">\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_btn_box -->\r\n");
      out.write("      <!-- // .slide_pagination -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- // .container -->\r\n");
      out.write("  \r\n");
      out.write("  <h1 class=\"title\">과일</h1>\r\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\r\n");
      out.write("   	<div class=\"slide_wrap slide4\">\r\n");
      out.write("      <div class=\"slide_box\">\r\n");
      out.write("        <div class=\"slide_list clearfix\">\r\n");
      out.write("       	");
 
    	ItemDao dao4 = new ItemDao();
    	List<ItemDto> list4 = dao.getListCategory("fruit", 0, 8);
    	
    	for(ItemDto dto: list4){
    		
       	
      out.write("\r\n");
      out.write("          <div class=\"slide_content slide01\">\r\n");
      out.write("          	<a href = \"#\" class = \"a\">\r\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\r\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\r\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\r\n");
      out.write("          	</a>\r\n");
      out.write("          </div>\r\n");
      out.write("         ");
 
    	}
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // .slide_list -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_box -->\r\n");
      out.write("      <div class=\"slide_btn_box\">\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_btn_box -->\r\n");
      out.write("      <!-- // .slide_pagination -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- // .container -->\r\n");
      out.write("  \r\n");
      out.write("  <h1 class=\"title\">베이커리</h1>\r\n");
      out.write("    <a href=\"#\" class=\"link\" target=\"_blank\"></a>\r\n");
      out.write("   	<div class=\"slide_wrap slide5\">\r\n");
      out.write("      <div class=\"slide_box\">\r\n");
      out.write("        <div class=\"slide_list clearfix\">\r\n");
      out.write("       	");
 
    	ItemDao dao5 = new ItemDao();
    	List<ItemDto> list5 = dao.getListCategory("bakery", 0, 8);
    	
    	for(ItemDto dto: list5){
    		
       	
      out.write("\r\n");
      out.write("          <div class=\"slide_content slide01\">\r\n");
      out.write("          	<a href = \"#\" class = \"a\">\r\n");
      out.write("          	<img src=\"itemImg/");
      out.print(dto.getItem_img() );
      out.write("\" width=\"275\">\r\n");
      out.write("          	<p>상품명 : ");
      out.print(dto.getItem_name());
      out.write("</p>\r\n");
      out.write("          	<p>가격 : ");
      out.print(dto.getItem_price() );
      out.write("원</p>\r\n");
      out.write("          	</a>\r\n");
      out.write("          </div>\r\n");
      out.write("         ");
 
    	}
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- // .slide_list -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_box -->\r\n");
      out.write("      <div class=\"slide_btn_box\">\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_prev\"><img src=\"image/arrow_left.png\" width=\"70\"></button>\r\n");
      out.write("        <button type=\"button\" class=\"slide_btn_next\"><img src=\"image/arrow_right14.png\" width=\"70\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- // .slide_btn_box -->\r\n");
      out.write("      <!-- // .slide_pagination -->\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- // .container -->\r\n");
      out.write("\r\n");
      out.write("  <script> \r\n");
      out.write("  	slide('.slide1');\r\n");
      out.write("  	slide('.slide2');\r\n");
      out.write("  	slide('.slide3');\r\n");
      out.write("  	slide('.slide4');\r\n");
      out.write("  	slide('.slide5');\r\n");
      out.write("  	\r\n");
      out.write("    function slide(root_name) {\r\n");
      out.write("      const root = document.querySelector(root_name);\r\n");
      out.write("      const slideList = root.querySelector('.slide_list');  // Slide parent dom\r\n");
      out.write("      const slideContents = root.querySelectorAll('.slide_content');  // each slide dom\r\n");
      out.write("      const slideBtnNext = root.querySelector('.slide_btn_next'); // next button\r\n");
      out.write("      const slideBtnPrev = root.querySelector('.slide_btn_prev'); // prev button\r\n");
      out.write("      const slideLen = slideContents.length;  // slide length\r\n");
      out.write("      const slideWidth = 1220; // slide width\r\n");
      out.write("      const slideSpeed = 300; // slide speed\r\n");
      out.write("      const startNum = 0; // initial slide index (0 ~ 4)\r\n");
      out.write("      \r\n");
      out.write("      slideList.style.width = slideWidth * (slideLen + 2) + \"px\";\r\n");
      out.write("      \r\n");
      out.write("      // Copy first and last slide\r\n");
      out.write("      let firstChild = slideList.firstElementChild;\r\n");
      out.write("      let lastChild = slideList.lastElementChild;\r\n");
      out.write("      let clonedFirst = firstChild.cloneNode(true);\r\n");
      out.write("      let clonedLast = lastChild.cloneNode(true);\r\n");
      out.write("\r\n");
      out.write("      // Add copied Slides\r\n");
      out.write("      slideList.appendChild(clonedFirst);\r\n");
      out.write("      slideList.insertBefore(clonedLast, slideList.firstElementChild);\r\n");
      out.write("\r\n");
      out.write("      // Add pagination dynamically\r\n");
      out.write("\r\n");
      out.write("      slideList.style.transform = \"translate3d(-\" + (slideWidth)*0 + \"px, 0px, 0px)\";\r\n");
      out.write("\r\n");
      out.write("      let curIndex = startNum; // current slide index (except copied slide)\r\n");
      out.write("      let curSlide = slideContents[curIndex]; // current slide dom\r\n");
      out.write("      \r\n");
      out.write("      var next=0;\r\n");
      out.write("\r\n");
      out.write("      /** Next Button Event */\r\n");
      out.write("      slideBtnNext.addEventListener('click', function() {\r\n");
      out.write("        if (curIndex < slideLen-4) {\r\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\r\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + (slideWidth * (next + 1)) + \"px, 0px, 0px)\";\r\n");
      out.write("\r\n");
      out.write("          if(curIndex<0){\r\n");
      out.write("        	  curIndex=0;\r\n");
      out.write("          }\r\n");
      out.write("          curIndex=curIndex+4;\r\n");
      out.write("          next=next+1;\r\n");
      out.write("          console.log(curIndex);\r\n");
      out.write("        }\r\n");
      out.write("        else if (curIndex >= slideLen-4) {\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            slideList.style.transition = \"1000ms\";\r\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + (slideWidth)*0 + \"px, 0px, 0px)\";\r\n");
      out.write("          }, slideSpeed);\r\n");
      out.write("          curIndex = 0;\r\n");
      out.write("          next=0;\r\n");
      out.write("          console.log(curIndex);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        curSlide = slideContents[curIndex];\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      /** Prev Button Event */\r\n");
      out.write("      slideBtnPrev.addEventListener('click', function() {\r\n");
      out.write("        if (curIndex > 0) {\r\n");
      out.write("          slideList.style.transition = slideSpeed + \"ms\";\r\n");
      out.write("          slideList.style.transform = \"translate3d(-\" + slideWidth*(next-1) + \"px, 0px, 0px)\";\r\n");
      out.write("          \r\n");
      out.write("          curIndex=curIndex-4;\r\n");
      out.write("          \r\n");
      out.write("          next=next-1;\r\n");
      out.write("          \r\n");
      out.write("          console.log(curIndex);\r\n");
      out.write("        }\r\n");
      out.write("        else if (curIndex <= 0) {\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            slideList.style.transition = \"1000ms\";\r\n");
      out.write("            slideList.style.transform = \"translate3d(-\" + slideWidth*(slideLen/4-1) + \"px, 0px, 0px)\";\r\n");
      out.write("          }, slideSpeed);\r\n");
      out.write("          curIndex = slideLen-4;\r\n");
      out.write("          next= slideLen/4-1;\r\n");
      out.write("          console.log(curIndex);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        curSlide = slideContents[curIndex];\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("    };\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
